import http from 'node:http';
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';

const __dirname=path.dirname(fileURLToPath(import.meta.url));
const DATA_DIR=path.join(__dirname,'data'); const UPLOAD_DIR=path.join(__dirname,'uploads');
fs.mkdirSync(DATA_DIR,{recursive:true}); fs.mkdirSync(UPLOAD_DIR,{recursive:true});
const DB_FILE=path.join(DATA_DIR,'database.json'); const execFileAsync=promisify(execFile); const save=()=>fs.writeFileSync(DB_FILE,JSON.stringify(db,null,2));
const jobsSeed=[
{id:'1',title:'Frontend Developer',company:'TechNova',location:'Hyderabad',skills:['React','JavaScript','CSS','Tailwind'],description:'Build responsive web applications and reusable UI components for our recruitment platform.',requirements:['Strong React and JavaScript fundamentals','Experience with responsive UI development','Knowledge of REST APIs and Git']},
{id:'2',title:'AI/ML Engineer',company:'DataSphere',location:'Bengaluru',skills:['Python','Machine Learning','TensorFlow','SQL'],description:'Develop and integrate machine learning solutions for candidate matching and recruitment analytics.',requirements:['Strong Python programming skills','Understanding of machine learning concepts','Experience with model APIs and data pipelines']},
{id:'3',title:'Full Stack Developer',company:'CloudWorks',location:'Pune',skills:['React','Node.js','MongoDB','JavaScript'],description:'Work across frontend and backend services to deliver scalable recruitment workflows.',requirements:['Experience with React and Node.js','Working knowledge of databases','Ability to build and consume REST APIs']},
{id:'4',title:'Backend Developer',company:'InnovateLabs',location:'Hyderabad',skills:['Node.js','Python','SQL','REST API'],description:'Build reliable backend services that support recruitment, evaluation, and reporting workflows.',requirements:['Strong backend development fundamentals','Experience with REST APIs','SQL/database knowledge']}];
const candidateSeeds=[
{id:'cand-1',name:'Aarav Sharma',email:'aarav@example.com',role:'Frontend Developer',score:92,technical:90,communication:88,confidence:95,experience:3,skills:['React','Tailwind','JavaScript'],location:'Bangalore',summary:'Strong frontend engineer with clean component architecture.'},
{id:'cand-2',name:'Priya Nair',email:'priya@example.com',role:'Backend Developer',score:87,technical:91,communication:80,confidence:89,experience:4,skills:['Python','FastAPI','SQL'],location:'Remote',summary:'Full-stack Python developer with strong API fundamentals.'},
{id:'cand-3',name:'Rohan Mehta',email:'rohan@example.com',role:'Frontend Developer',score:78,technical:75,communication:82,confidence:76,experience:1,skills:['React','CSS'],location:'Hyderabad',summary:'Frontend specialist focused on responsive web interfaces.'},
{id:'cand-4',name:'Sneha Iyer',email:'sneha@example.com',role:'AI Engineer',score:95,technical:97,communication:90,confidence:96,experience:5,skills:['Python','LangChain','NLP','Machine Learning'],location:'Chennai',summary:'AI engineer with strong NLP and machine-learning fundamentals.'},
{id:'cand-5',name:'Karan Verma',email:'karan@example.com',role:'Backend Developer',score:65,technical:60,communication:70,confidence:64,experience:2,skills:['Node.js','MongoDB'],location:'Hyderabad',summary:'Backend developer with practical Node.js experience.'}];
function fresh(){return{users:[],jobs:jobsSeed,applications:[],notifications:[],interviews:[],candidates:candidateSeeds,settings:{},resetTokens:[]}}
let db; try{db=fs.existsSync(DB_FILE)?JSON.parse(fs.readFileSync(DB_FILE,'utf8')):fresh()}catch{db=fresh()}; const base=fresh(); for(const k in base)if(db[k]===undefined)db[k]=base[k]; if(db.users.length===0){ db.users.push({id:'demo-candidate',name:'Demo Candidate',email:'candidate@demo.com',passwordHash:hashPassword('Demo1234'),role:'candidate',phone:'',location:'Hyderabad',skills:['React','JavaScript','SQL'],resumeName:'',overallMatchScore:75,notificationPreferences:{email:true,in_app:true,interview_updates:true},createdAt:new Date().toISOString()},{id:'demo-recruiter',name:'Demo Recruiter',email:'recruiter@demo.com',passwordHash:hashPassword('Demo1234'),role:'recruiter',phone:'',location:'Hyderabad',skills:[],notificationPreferences:{email:true,in_app:true,interview_updates:true},createdAt:new Date().toISOString()}); save(); }
const id=(p='id')=>`${p}-${crypto.randomUUID()}`;
function hashPassword(p,salt=crypto.randomBytes(16).toString('hex')){return `${salt}:${crypto.scryptSync(p,salt,64).toString('hex')}`}
function verifyPassword(p,stored){try{const [salt,h]=String(stored).split(':');const a=crypto.scryptSync(p,salt,64).toString('hex');return crypto.timingSafeEqual(Buffer.from(a,'hex'),Buffer.from(h,'hex'))}catch{return false}}
const SECRET=process.env.JWT_SECRET||'ai-hr-development-secret-change-me';
function sign(u){const payload=Buffer.from(JSON.stringify({id:u.id,role:u.role,exp:Date.now()+604800000})).toString('base64url');return payload+'.'+crypto.createHmac('sha256',SECRET).update(payload).digest('base64url')}
function userPublic(u){return{id:u.id,name:u.name,email:u.email,role:u.role,phone:u.phone||'',location:u.location||'',skills:u.skills||[]}}
function scoreJob(job,skills=[]){const s=new Set(skills.map(x=>x.toLowerCase()));return Math.round(job.skills.filter(x=>s.has(x.toLowerCase())).length/Math.max(job.skills.length,1)*100)}
function notify(userId,title,message){db.notifications.push({id:id('notification'),userId,title,message,read:false,createdAt:new Date().toISOString()})}
function parseAuth(req){const h=req.headers.authorization||'';if(!h.startsWith('Bearer '))return null;try{const [p,s]=h.slice(7).split('.');const e=crypto.createHmac('sha256',SECRET).update(p).digest('base64url');if(!s||!crypto.timingSafeEqual(Buffer.from(s),Buffer.from(e)))return null;const d=JSON.parse(Buffer.from(p,'base64url').toString());if(d.exp<Date.now())return null;return db.users.find(u=>u.id===d.id)||null}catch{return null}}
function send(res,status,data,headers={}){const body=data===undefined||data===null?'':JSON.stringify(data);res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Content-Type, Authorization','Access-Control-Allow-Methods':'GET,POST,PATCH,OPTIONS',...headers});res.end(body)}
async function body(req){return await new Promise((resolve,reject)=>{const chunks=[];let size=0;req.on('data',c=>{size+=c.length;if(size>7*1024*1024){req.destroy();reject(new Error('Payload too large'));}else chunks.push(c)});req.on('end',()=>{const raw=Buffer.concat(chunks);if(!raw.length)return resolve({});const type=req.headers['content-type']||'';if(type.includes('application/json')){try{return resolve(JSON.parse(raw.toString()))}catch{return resolve({})}}resolve({raw,type})});req.on('error',reject)})}
async function multipart(req){const data=await body(req); if(!data.raw) return null; const boundary=data.type.match(/boundary=([^;]+)/)?.[1]; if(!boundary)return null; const buf=data.raw; const mark=Buffer.from('--'+boundary); let pos=0; let file=null; while((pos=buf.indexOf(mark,pos))!==-1){let start=pos+mark.length;if(buf[start]===45)break; if(buf[start]===13&&buf[start+1]===10)start+=2; const end=buf.indexOf(mark,start); if(end===-1)break; const part=buf.subarray(start,end); const sep=Buffer.from('\r\n\r\n'); const hs=part.indexOf(sep); if(hs!==-1){const headers=part.subarray(0,hs).toString();const content=part.subarray(hs+4,part.length-2);const fn=headers.match(/filename="([^"]+)"/i)?.[1];if(fn)file={filename:fn,data:content,contentType:headers.match(/Content-Type:\s*([^\r\n]+)/i)?.[1]||'application/octet-stream'}} pos=end} return file}
const skills=['Python','Java','JavaScript','React','Node.js','SQL','MongoDB','AWS','Docker','Machine Learning','TensorFlow','NLP','FastAPI','Django','CSS','Tailwind','TypeScript','Git','REST API'];
function parseResume(text,filename){const lower=text.toLowerCase();const found=skills.filter(s=>lower.includes(s.toLowerCase()));const exp=(text.match(/(\d+(?:\.\d+)?)\s*(?:\+\s*)?(?:years?|yrs?)/i)||[])[1];const email=(text.match(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/i)||[])[0]||'';const phone=(text.match(/(?:\+91[-\s]?)?[6-9]\d{9}/)||[])[0]||'';const name=(text.split(/\r?\n/).map(x=>x.trim()).find(x=>x&&x.length<60&&!/resume|curriculum|email|phone|github|linkedin/i.test(x))||filename.replace(/\.pdf$/i,''));const education=(text.match(/(?:B\.?Tech|B\.?E|M\.?Tech|M\.?S|BSc|MSc)[^\n]*/i)||[])[0]||'Not detected';return{name,skills:found,experience:exp?`${exp} years`:'Not detected',education:education.trim(),email,phone}}
async function extractPdf(file){try{return(await execFileAsync('pdftotext',['-layout',file,'-'],{maxBuffer:5*1024*1024})).stdout}catch{return''}}
async function route(req,res){if(req.method==='OPTIONS')return send(res,204);const url=new URL(req.url,'http://localhost');const pathName=url.pathname;const method=req.method;
if(method==='GET'&&pathName==='/api/health')return send(res,200,{ok:true,service:'AI-HR-Recruitment-Simulator API'});
const u=parseAuth(req); const publicPaths=['/api/health','/api/auth/register','/api/auth/login','/api/auth/forgot-password']; const needsAuth=pathName.startsWith('/api/')&&!publicPaths.includes(pathName); if(needsAuth&&!u)return send(res,401,{detail:'Authentication required.'});
try{
if(method==='POST'&&pathName==='/api/auth/register'){const b=await body(req);const {name,email,password,role='candidate'}=b;if(!name||!email||!password)return send(res,400,{detail:'Name, email and password are required.'});if(password.length<8)return send(res,400,{detail:'Password must be at least 8 characters.'});const e=email.trim().toLowerCase();if(db.users.some(x=>x.email===e))return send(res,409,{detail:'An account with this email already exists.'});const user={id:id('user'),name:name.trim(),email:e,passwordHash:hashPassword(password),role:role==='recruiter'?'recruiter':'candidate',phone:'',location:'',skills:[],resumeName:'',overallMatchScore:0,notificationPreferences:{email:true,in_app:true,interview_updates:true},createdAt:new Date().toISOString()};db.users.push(user);save();return send(res,201,{user:userPublic(user),token:sign(user)})}
if(method==='POST'&&pathName==='/api/auth/login'){const b=await body(req);const user=db.users.find(x=>x.email===String(b.email||'').trim().toLowerCase());if(!user||!verifyPassword(String(b.password||''),user.passwordHash))return send(res,401,{detail:'Invalid email or password.'});return send(res,200,{user:userPublic(user),token:sign(user)})}
if(method==='POST'&&pathName==='/api/auth/forgot-password'){const b=await body(req);const user=db.users.find(x=>x.email===String(b.email||'').trim().toLowerCase());if(user){const token=id('reset');db.resetTokens.push({token,userId:user.id,expiresAt:Date.now()+900000});save()}return send(res,200,{message:'If an account exists for that email, a reset request has been created.'})}
if(method==='POST'&&pathName==='/api/auth/change-password'){const b=await body(req);if(!verifyPassword(String(b.current_password||''),u.passwordHash))return send(res,400,{detail:'Current password is incorrect.'});if(String(b.new_password||'').length<8)return send(res,400,{detail:'New password must be at least 8 characters.'});u.passwordHash=hashPassword(b.new_password);save();return send(res,204)}
if(method==='GET'&&pathName==='/api/jobs'){if(u.role!=='candidate'&&u.role!=='recruiter')return send(res,403,{detail:'Forbidden'});return send(res,200,db.jobs.map(j=>({...j,matchScore:u.role==='candidate'?scoreJob(j,u.skills):undefined})))}
if(method==='GET'&&/^\/api\/jobs\/[^/]+$/.test(pathName)){const job=db.jobs.find(j=>j.id===pathName.split('/').pop());if(!job)return send(res,404,{detail:'Job not found.'});return send(res,200,{...job,matchScore:u.role==='candidate'?scoreJob(job,u.skills):undefined})}
if(method==='POST'&&/^\/api\/jobs\/[^/]+\/apply$/.test(pathName)){if(u.role!=='candidate')return send(res,403,{detail:'Only candidates can apply.'});const job=db.jobs.find(j=>j.id===pathName.split('/')[3]);if(!job)return send(res,404,{detail:'Job not found.'});if(db.applications.some(a=>a.jobId===job.id&&a.candidateId===u.id))return send(res,409,{detail:'You already applied for this job.'});const a={id:id('application'),candidateId:u.id,jobId:job.id,title:job.title,company:job.company,location:job.location,matchScore:scoreJob(job,u.skills),status:'Applied',createdAt:new Date().toISOString()};db.applications.push(a);notify(u.id,'Application submitted',`Your application for ${job.title} at ${job.company} was submitted.`);save();return send(res,201,a)}
if(method==='GET'&&pathName==='/api/candidate/profile'){if(u.role!=='candidate')return send(res,403,{detail:'Candidate access required.'});return send(res,200,{...userPublic(u),resumeName:u.resumeName,overallMatchScore:u.overallMatchScore})}
if(method==='PATCH'&&pathName==='/api/candidate/profile'){if(u.role!=='candidate')return send(res,403,{detail:'Candidate access required.'});const b=await body(req);for(const k of ['name','phone','location','skills','resumeName'])if(b[k]!==undefined)u[k]=b[k];u.overallMatchScore=Math.round(db.jobs.reduce((s,j)=>s+scoreJob(j,u.skills),0)/db.jobs.length);save();return send(res,200,{...userPublic(u),resumeName:u.resumeName,overallMatchScore:u.overallMatchScore})}
if(method==='GET'&&pathName==='/api/candidate/applications'){if(u.role!=='candidate')return send(res,403,{detail:'Candidate access required.'});return send(res,200,db.applications.filter(a=>a.candidateId===u.id).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)))}
if(method==='GET'&&pathName==='/api/candidates'){if(u.role!=='recruiter')return send(res,403,{detail:'Recruiter access required.'});return send(res,200,[...db.candidates].sort((a,b)=>b.score-a.score))}
if(method==='GET'&&pathName==='/api/notifications')return send(res,200,db.notifications.filter(n=>n.userId===u.id).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)));
if(method==='PATCH'&&/^\/api\/notifications\/[^/]+\/read$/.test(pathName)){const n=db.notifications.find(x=>x.id===pathName.split('/')[3]&&x.userId===u.id);if(!n)return send(res,404,{detail:'Notification not found.'});n.read=true;save();return send(res,204)}
if(method==='GET'&&pathName==='/api/settings')return send(res,200,{notification_preferences:u.notificationPreferences});
if(method==='PATCH'&&pathName==='/api/settings/notifications'){const b=await body(req);u.notificationPreferences={...u.notificationPreferences,...b};save();return send(res,200,u.notificationPreferences)}
if(method==='POST'&&pathName==='/api/resume/upload'){if(u.role!=='candidate')return send(res,403,{detail:'Candidate access required.'});const f=await multipart(req);if(!f)return send(res,400,{detail:'Resume file is required.'});if(!/\.pdf$/i.test(f.filename))return send(res,400,{detail:'Only PDF files are accepted.'});if(f.data.length>5*1024*1024)return send(res,413,{detail:'File is too large. Maximum size is 5MB.'});const saved=path.join(UPLOAD_DIR,`${Date.now()}-${crypto.randomUUID()}.pdf`);fs.writeFileSync(saved,f.data);const text=await extractPdf(saved);const parsed=parseResume(text,f.filename);u.name=parsed.name||u.name;u.phone=parsed.phone||u.phone;u.skills=[...new Set(parsed.skills)];u.resumeName=f.filename;u.overallMatchScore=Math.round(db.jobs.reduce((s,j)=>s+scoreJob(j,u.skills),0)/db.jobs.length);const c=db.candidates.find(x=>x.email===u.email);if(c){c.name=u.name;c.skills=u.skills;c.score=Math.max(c.score,u.overallMatchScore)}save();return send(res,200,{...parsed,overallMatchScore:u.overallMatchScore})}
if(method==='POST'&&pathName==='/api/copilot/query'){if(u.role!=='recruiter')return send(res,403,{detail:'Recruiter access required.'});const b=await body(req);const q=String(b.query||'').toLowerCase(),f=b.filters||{};const top=Number((q.match(/top\s+(\d+)/)||[])[1]||5);const min=Number((q.match(/(?:above|over|>=?)\s*(\d{2})/)||[])[1]||f.minScore||0);const loc=String(f.location||['bangalore','chennai','hyderabad','remote'].find(x=>q.includes(x))||'').toLowerCase();const rs=[...(f.skills||[]),...skills.filter(s=>q.includes(s.toLowerCase()))].map(x=>x.toLowerCase());let cs=db.candidates.filter(c=>c.score>=min&&(!loc||c.location.toLowerCase()===loc)&&rs.every(s=>c.skills.some(x=>x.toLowerCase()===s))).sort((a,b)=>b.score-a.score).slice(0,top);return send(res,200,{reply:cs.length?`Found ${cs.length} matching candidates. ${cs[0].name} leads with ${cs[0].score}%.`:'I could not find candidates matching those filters. Try relaxing the score, skill, or location.',candidates:cs})}
if(method==='POST'&&/^\/api\/interview\/[^/]+\/answer$/.test(pathName)){const b=await body(req);const text=String(b.answer||''),words=text.trim().split(/\s+/).filter(Boolean).length;const technical=Math.min(100,50+Math.min(35,Math.round(words*1.2))),communication=Math.min(100,55+Math.min(40,Math.round(words*.9))),confidence=Math.min(100,50+Math.min(45,Math.round(words*.8)));const r={id:id('answer'),candidateId:pathName.split('/')[3],userId:u.id,question:b.question||'',answer:text,index:Number(b.index||0),technical,communication,confidence,createdAt:new Date().toISOString()};db.interviews.push(r);save();return send(res,200,{message:'Answer recorded.',evaluation:{technical,communication,confidence,score:Math.round((technical+communication+confidence)/3)}})}
return send(res,404,{detail:'API endpoint not found.'})
}catch(e){console.error(e);return send(res,500,{detail:e.message||'Server error.'})}}
const PORT=Number(process.env.PORT||8000);http.createServer((req,res)=>route(req,res)).listen(PORT,()=>console.log(`AI-HR API running at http://localhost:${PORT}`));
